#include<stdio.h>
#include<limits.h>
#include<float.h>
int main()
{
	printf("CHAR_BIT:%d\n",CHAR_BIT);	
	printf("CHAR_MAX:%d\n",CHAR_MAX);
	printf("CHAR_MIN:%d\n",CHAR_MIN);
	printf("SCHAR_MAX:%d\n",SCHAR_MAX);
	printf("SCHAR_MIN:%d\n",SCHAR_MIN);
	printf("UCHAR_MAX:%d\n",UCHAR_MAX);
	printf("SHRT_MIN:%d\n",SHRT_MIN);
	printf("SHRT_MAX:%d\n",SHRT_MAX);
	printf("USHRT_MAX:%d\n",USHRT_MAX);
	printf("INT_MIN:%d\n",INT_MIN);
	printf("INT_MAX:%d\n",INT_MAX);
	printf("UINT_MAX:%d\n",UINT_MAX);
	printf("LONG_MAX:%d\n",LONG_MAX);
	printf("LONG_MIN:%d\n",LONG_MIN);
	printf("ULONG_MAX:%d\n",ULONG_MAX);
	printf("LONG_LONG_MIN:%d\n",LONG_LONG_MIN);
	printf("LONG_LONG_MAX:%d\n",LONG_LONG_MAX);
	printf("ULONG_LONG_MAX:%d\n",ULONG_LONG_MAX);
	printf("\n");
	printf("float类型的尾数位数:%d\n",FLT_MANT_DIG);
	printf("float最小有效数字位数:%d\n",FLT_DIG);
	printf("float负指数的最小值:%d\n",FLT_MIN_10_EXP);
	printf("float正指数的最大值:%d\n",FLT_MAX_10_EXP);
	printf("float类型正数的最大值:%d\n",FLT_MAX);
	printf("\n");
	
}
